### ISSUE TITLE
Various drillcore search view issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/eurocore#7]
The drillcore search view has a number of style and UI logic issues (maybe need to split the ticket):
* it is not practical not nice to duplicate search field name in label as well as in placeholder text - maybe placeholder is enough.
* autocomplete is using different style (font, box), shuld use same style as the search boxes.
* autocomplete does not work in ipad (safari, chrome)
* in search field ENTER should start the search (in addition to button)
* if no results found, show message "No results found. Please try again or select a drillcore from the list for details", and then the list as if no search was made. Never display table header when there are no data rows. 
* results table should scale to full container width, not leaving empty space on right
* dip column should not be a link
* paging control should not be shown if only 1 page; control should be in same row with "Found N results", aligned right, so that the vertical position of results table would not jump up and down.
* black table header is too "heavy" and prominent
* page title should be set to something meaningful like EUROCORE Data Portal
* Angular logo should be removed from header and favicon, favicon could be taken from arendus.geokogud.info
* map should have dynamic width (width: 100%; min-width: 300px;)
* map shouldnt have br-tag before
* map should have padding so that id does not touch the search button or results table 
* map should always display all boreholes, but those selected in different color
* better use vector marker instead of png
* add map layers swicher control, and change default base layer to something nicer, like used in geokogud.info (http://geokogud.info/locality/2)
* add zoomin zoomout rectangle select buttons to map
* one click select on map should select multiple cores if their markers overlap

**Comment by karel90** [comment]
The drillcore search view has a number of style and UI logic issues (maybe need to split the ticket):
* ~~it is not practical not nice to duplicate search field name in label as well as in placeholder text - maybe placeholder is enough.~~
* autocomplete is using different style (font, box), shuld use same style as the search boxes.
* autocomplete does not work in ipad (safari, chrome)
* ~~in search field ENTER should start the search (in addition to button)~~
* ~~if no results found, show message "No results found. Please try again or select a drillcore from the list for details", and then the list as if no search was made. Never display table header when there are no data rows.~~
* ~~results table should scale to full container width, not leaving empty space on right~~
* ~~dip column should not be a link~~
* ~~paging control should not be shown if only 1 page; control should be in same row with "Found N results", aligned right, so that the vertical position of results table would not jump up and down.~~
* ~~black table header is too "heavy" and prominent~~
* ~~page title should be set to something meaningful like EUROCORE Data Portal~~
* ~~Angular logo should be removed from header and favicon, favicon could be taken from arendus.geokogud.info~~
* ~~map should have dynamic width (width: 100%; min-width: 300px;)~~
* ~~map shouldnt have br-tag before~~
* ~~map should have padding so that id does not touch the search button or results table~~
* map should always display all boreholes, but those selected in different color
* ~~better use vector marker instead of png~~
* add map layers swicher control, and change default base layer to something nicer, like used in geokogud.info (http://geokogud.info/locality/2)
* ~~add zoomin zoomout rectangle select buttons to map~~
* one click select on map should select multiple cores if their markers overlap
